package com.publicmart.android.Utils;

public interface CONSTANTS {

    String UserName="UserName";

    String UserPwd="UserPwd";
    String AppToken="AppToken";
    String Mode="Mode";
    String CustKey="CustKey";
    String CustomerName="CustomerName";
    String MobileNo="MobileNo";
    String Email="Email";
    String SponsorId="SponsorId";
    String MSTypeKey="MSTypeKey";
    String Status="Status";
    String CreatedBy="CreatedBy";
    String ImgURL_="http://bos.publicmart.in";
    String LocalURL_="http://bos.publicmart.in";

    String AdvImageKey = "AdvImageKey";
    String ImageDesc = "ImageDesc";
    String ImagePath = "ImagePath";
    String CategoryKey ="CategoryKey";
    String CategoryName = "CategoryName";
    String NUMBER ="NUMBER" ;
    String ProductKey = "ProductKey";
    String BrandName = "BrandName";
    String ShortDesc = "ShortDesc";
    String MRP = "MRP";
    String BV = "BV";
    String PageNumber = "PageNumber";
    String PageSize = "PageSize";
    String ProductCode = "ProductCode";
    String ProductDetails = "ProductDetails";
    String Material = "Material";
    String Size = "Size";
    String Color = "Color";
    String ProductImageID = "ProductImageID";
    String Qty = "Qty";
    String Rate ="Rate" ;
    String IsCredit = "IsCredit";
    String OrderStatusKey = "OrderStatusKey";
    String OrderKey = "OrderKey";
    String Amount = "Amount";
    String OrderStatusName = "OrderStatusName";
    String AirportKey = "AirportKey";
    String ShortCode = "ShortCode";
    String AirportName = "AirportName";
    String StationKey = "StationKey";
    String StationName = "StationName";
    String PassengerName="PassengerName" ;
    String DOB = "DOB";
    String FromAirportKey = "FromAirportKey";
    String ToAirportKey ="ToAirportKey" ;
    String TravelDate = "TravelDate";
    String ContactEmail = "ContactEmail";
    String ContactNo = "ContactNo" ;
    String BookingStatusKey = "BookingStatusKey";
    String Age = "Age";
    String FromStationKey = "FromStationKey";
    String ToStationKey = "ToStationKey";
    String CruiseType = "CruiseType";
    String GuestNos ="GuestNos" ;
    String FlightBookingKey = "FlightBookingKey";
    String FromAirportCode = "FromAirportCode";
    String ToAirportCode = "ToAirportCode";
    String BookingStatusName = "BookingStatusName";
    String Type = "Type";
    String TrainBookingKey = "TrainBookingKey";
    String FromStationCode = "FromStationCode";
    String ToStationCode = "ToStationCode";
    String HBBookingKey = "HBBookingKey" ;
    String BookingKey = "BookingKey";
}
